logging.level:
  ru.yandex.practicum.filmorate: DEBUG
  org.zalando.logbook: WARN

spring:
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

